### ISSUE TITLE
About the type of imges

### ISSUE THREAD

**Issue by DaxingZ** [xinntao/HandyView#12]
Thanks for your good job!
Unfortunately when I want to open .tif images, it is failed to work showing that 'Wrong init path! '. Therefore, could you account for which types this project will support?

**Comment by xinntao** [comment]
![image](https://user-images.githubusercontent.com/17445847/129856656-70099939-4905-4dea-a2a6-bca68656e172.png)

Is tif the same as tiff?

**Comment by DaxingZ** [comment]
Whoops,it seems the same format with different name🤣Just like .jpg &.jpeg or .doc&.docx.
They can interchange straightly.
