### ISSUE TITLE
draw功能失效> <

### ISSUE THREAD

**Issue by DaxingZ** [xinntao/HandyView#14]
你好xinntao！谢谢你的实用小脚本！在图像超分处理结果时非常有用！
而我在使用draw功能想要圈出细节范围时，点了菜单栏的draw没有反应，重新下载后，又换了不同的图都没有反应，也没有像你演示的图中那样光标小手变黄。所以可能是我使用方式不对？

**Comment by TaoWangzj** [comment]
meet the same problem

**Comment by xinntao** [comment]
Draw: 目前这个功能比较简单， 是按住 shift 拖拽 鼠标实现的
