### ISSUE TITLE
fix a small mistake

### ISSUE THREAD

**Issue by stevenxmy** [xinntao/HandyView#16]
'pyinstaller -D handyview/handyview.py -i icon.ico --windowed'
should be 
'pyinstaller -D handyview/handyview**_er_**.py -i icon.ico --windowed'

BTW, in 'handyviewer.py', 'sys.path.append('./')' should be added to avoid the 'no module' error

**Comment by james-see** [comment]
@stevenxmy can you consider doing a pull request with these changes? I came here after getting the no module error.

**Comment by xinntao** [comment]
We have updated the codes. 
If you still encounter this issue, please re-open it. Thanks :-)
