### ISSUE TITLE
Will you support simultaneous zooming in the case of multi-view comparison？

### ISSUE THREAD

**Issue by jiuzhuanzhuan** [xinntao/HandyView#9]
Hi，
    Thank u for your great job, it is useful.
    **platform**: windows10
    **version**:released v0.4.2

~~1.  In actual use, I found that when comparing multiple views, it is best to zoom in or zoom out at the same time， will u support this oneday？~~
2. When dragging the mouse to draw the frame, it did‘t display any info on the right.
 Sorry，I found first item in your todolist，i just have the other question.

**Comment by xinntao** [comment]
@jiuzhuanzhuan 
Thanks for the feedback.

I am going to update it. But I may not be free these days =-= 
If you could help to improve it, it would be great.

For the second point, could you explain more?
